name: Atividade 02.2 – Acrescentando novas etapas ao workflow

on:
  push:
jobs:
  primeiro-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Primeiro passo"
      - name: Checkout
        uses: actions/checkout@v5
      - name: Data e hora da execução
        run: date
      - name: Sistema operacional do runner
        run: echo "Runner OS: ${{ runner.os }}" && uname -a
      - name: Versão do Git
        run: git --version
      - name: Conteúdo do README
        run: cat README.md
      - name: Lista arquivos inicial
        run: ls ${{ github.workspace }}
      - name: Status
        run: echo "Status ${{ job.status }}."