name: Atividade 2.3 - Utilizando Variaveis

on:
  push:

env:
  CURSO: "Integração Contínua"

jobs:
  exibir-contexto:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Exibir informacoes do workflow
        run: |
          echo "Nome do Curso: ${{ env.CURSO }}"
          echo "Usuario executor: ${{ github.actor }}"
          echo "Nome do repositorio: ${{ github.repository }}"
          echo "Branch utilizada: ${{ github.ref_name }}"