name: Atividade 2.2 - Novas Etapas

on:
  push:

jobs:
  executar-etapas:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Exibir data e hora da execucao
        run: date

      - name: Exibir sistema operacional do runner
        run: echo "O SO utilizado e o $RUNNER_OS"

      - name: Exibir versao do Git
        run: git --version

      - name: Exibir conteudo do README.md
        run: cat README.md

      - name: Listar arquivos novamente
        run: ls -la